In [24]:
import torch
import transformers
from transformers import (AutoTokenizer, AutoModelForSequenceClassification)

In [ ]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint) # install the tokenizer

In [12]:
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")
print(f"inputs.input_ids: \n{inputs.input_ids}") # 2 lines of tokens, foreach sentences in raw_inputs
print(f"\ninputs.attention_mask: \n{inputs.attention_mask}")

inputs.input_ids: 
tensor([[  101,  1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,
          2607,  2026,  2878,  2166,  1012,   102],
        [  101,  1045,  5223,  2023,  2061,  2172,   999,   102,     0,     0,
             0,     0,     0,     0,     0,     0]])

inputs.attention_mask: 
tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]])


In [25]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [31]:
outputs = model(**inputs)

In [32]:
print(outputs.logits.shape)
print(outputs.logits)

torch.Size([2, 2])
tensor([[-1.5607,  1.6123],
        [ 4.1692, -3.3464]], grad_fn=<AddmmBackward0>)


In [36]:
# predictions
pred = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(pred)

tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


In [37]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}

In [38]:
"""
    première phrase : NEGATIVE: 0.0402, POSITIVE: 0.9598
    deuxième phrase : NEGATIVE: 0.9995, POSITIVE: 0.0005
"""

'\n    première phrase : NEGATIVE: 0.0402, POSITIVE: 0.9598\n    deuxième phrase : NEGATIVE: 0.9995, POSITIVE: 0.0005\n'

In [ ]:
# Resume all

import torch
from transformers import (AutoTokenizer, AutoModelForSequenceClassification)

# charge tokenizer
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

# inputs txt
raw_inputs = [
    "I've been waiting for a HuggingFace course my whole life.",
    "I hate this so much!",
]

inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

# charge the transformer model
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

outputs = model(**inputs)
#print(outputs.logits)

# predictions
pred = torch.nn.functional.softmax(outputs.logits, dim=-1)
print(f"pred: {pred}")

# label of the transformers model
model.config.id2label

pred: tensor([[4.0195e-02, 9.5980e-01],
        [9.9946e-01, 5.4418e-04]], grad_fn=<SoftmaxBackward0>)


{0: 'NEGATIVE', 1: 'POSITIVE'}